[package]
name = "vn_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.16.1", features = ["jpeg", "png"] }
serde = "1.0.219"
serde_yaml = "0.9.34"
